# Generated by Django 4.2 on 2025-03-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptorKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KeyName', models.CharField(max_length=255)),
                ('KeyValue', models.CharField(max_length=100)),
            ],
        ),
    ]
